-- ===========================================================================
-- Non-destructive migration: expand seat maps to full 5-row layouts (40/theatre)
-- Run ONCE against a DB created from the ORIGINAL seed (29 seats / 32 show_seats).
-- Preserves existing users, bookings and payments. Idempotent on seats via INSERT IGNORE.
-- Usage: mysql -u root -p BMSDec24 < db/migration_expand_seat_rows.sql
-- ===========================================================================

-- 1) Re-label pinned seat ids 10-29 to A1/A2 GOLD (theatres 3-12) so rows B-E align.
UPDATE seats SET seat_number='A1', seat_type='GOLD', price=280 WHERE id=10;
UPDATE seats SET seat_number='A2', seat_type='GOLD', price=280 WHERE id=11;
UPDATE seats SET seat_number='A1', seat_type='GOLD', price=250 WHERE id=12;
UPDATE seats SET seat_number='A2', seat_type='GOLD', price=250 WHERE id=13;
UPDATE seats SET seat_number='A1', seat_type='GOLD', price=270 WHERE id=14;
UPDATE seats SET seat_number='A2', seat_type='GOLD', price=270 WHERE id=15;
UPDATE seats SET seat_number='A1', seat_type='GOLD', price=240 WHERE id=16;
UPDATE seats SET seat_number='A2', seat_type='GOLD', price=240 WHERE id=17;
UPDATE seats SET seat_number='A1', seat_type='GOLD', price=260 WHERE id=18;
UPDATE seats SET seat_number='A2', seat_type='GOLD', price=260 WHERE id=19;
UPDATE seats SET seat_number='A1', seat_type='GOLD', price=270 WHERE id=20;
UPDATE seats SET seat_number='A2', seat_type='GOLD', price=270 WHERE id=21;
UPDATE seats SET seat_number='A1', seat_type='GOLD', price=255 WHERE id=22;
UPDATE seats SET seat_number='A2', seat_type='GOLD', price=255 WHERE id=23;
UPDATE seats SET seat_number='A1', seat_type='GOLD', price=265 WHERE id=24;
UPDATE seats SET seat_number='A2', seat_type='GOLD', price=265 WHERE id=25;
UPDATE seats SET seat_number='A1', seat_type='GOLD', price=265 WHERE id=26;
UPDATE seats SET seat_number='A2', seat_type='GOLD', price=265 WHERE id=27;
UPDATE seats SET seat_number='A1', seat_type='GOLD', price=275 WHERE id=28;
UPDATE seats SET seat_number='A2', seat_type='GOLD', price=275 WHERE id=29;

-- 2) Add remaining seats for demo theatres 1-2 (ids 30-100).
INSERT IGNORE INTO seats (id, seat_number, seat_type, price, seat_status, theatre_id, booked_by_user_id, theatre_name, booked_by_user_name, created_at, updated_at) VALUES
  (30, 'A3', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (31, 'A4', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (32, 'A5', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (33, 'A6', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (34, 'A7', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (35, 'A8', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (36, 'B3', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (37, 'B4', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (38, 'B5', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (39, 'B6', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (40, 'B7', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (41, 'B8', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (42, 'C2', 'PLATINUM', 330.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (43, 'C3', 'PLATINUM', 330.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (44, 'C4', 'PLATINUM', 330.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (45, 'C5', 'PLATINUM', 330.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (46, 'C6', 'PLATINUM', 330.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (47, 'C7', 'PLATINUM', 330.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (48, 'C8', 'PLATINUM', 330.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (49, 'D1', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (50, 'D2', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (51, 'D3', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (52, 'D4', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (53, 'D5', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (54, 'D6', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (55, 'D7', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (56, 'D8', 'GOLD',     250.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (57, 'E1', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (58, 'E2', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (59, 'E3', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (60, 'E4', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (61, 'E5', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (62, 'E6', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (63, 'E7', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  (64, 'E8', 'SILVER',   180.0, 'AVAILABLE', 1, NULL, 'Orion PVR', NULL, NOW(), NOW()),
  -- PVR Phoenix (theatre 2): A3-A8, B2-B8, C2-C8, D1-D8, E1-E8
  (65, 'A3', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (66, 'A4', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (67, 'A5', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (68, 'A6', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (69, 'A7', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (70, 'A8', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (71, 'B2', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (72, 'B3', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (73, 'B4', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (74, 'B5', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (75, 'B6', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (76, 'B7', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (77, 'B8', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (78, 'C2', 'PLATINUM', 380.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (79, 'C3', 'PLATINUM', 380.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (80, 'C4', 'PLATINUM', 380.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (81, 'C5', 'PLATINUM', 380.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (82, 'C6', 'PLATINUM', 380.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (83, 'C7', 'PLATINUM', 380.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (84, 'C8', 'PLATINUM', 380.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (85, 'D1', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (86, 'D2', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (87, 'D3', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (88, 'D4', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (89, 'D5', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (90, 'D6', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (91, 'D7', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (92, 'D8', 'GOLD',     300.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (93, 'E1', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (94, 'E2', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (95, 'E3', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (96, 'E4', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (97, 'E5', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (98, 'E6', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (99, 'E7', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW()),
  (100,'E8', 'SILVER',   220.0, 'AVAILABLE', 2, NULL, 'PVR Phoenix', NULL, NOW(), NOW());

-- 3) Add remaining seats for theatres 3-12 (ids 101-480).
INSERT IGNORE INTO seats (id, seat_number, seat_type, price, seat_status, theatre_id, booked_by_user_id, theatre_name, booked_by_user_name, created_at, updated_at) VALUES
  (101, 'A3', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (102, 'A4', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (103, 'A5', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (104, 'A6', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (105, 'A7', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (106, 'A8', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (107, 'B1', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (108, 'B2', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (109, 'B3', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (110, 'B4', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (111, 'B5', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (112, 'B6', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (113, 'B7', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (114, 'B8', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (115, 'C1', 'PLATINUM', 360, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (116, 'C2', 'PLATINUM', 360, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (117, 'C3', 'PLATINUM', 360, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (118, 'C4', 'PLATINUM', 360, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (119, 'C5', 'PLATINUM', 360, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (120, 'C6', 'PLATINUM', 360, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (121, 'C7', 'PLATINUM', 360, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (122, 'C8', 'PLATINUM', 360, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (123, 'D1', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (124, 'D2', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (125, 'D3', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (126, 'D4', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (127, 'D5', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (128, 'D6', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (129, 'D7', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (130, 'D8', 'GOLD', 280, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (131, 'E1', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (132, 'E2', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (133, 'E3', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (134, 'E4', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (135, 'E5', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (136, 'E6', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (137, 'E7', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (138, 'E8', 'SILVER', 210, 'AVAILABLE', 3, NULL, 'PVR Select Citywalk', NULL, NOW(), NOW()),
  (139, 'A3', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (140, 'A4', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (141, 'A5', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (142, 'A6', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (143, 'A7', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (144, 'A8', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (145, 'B1', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (146, 'B2', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (147, 'B3', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (148, 'B4', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (149, 'B5', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (150, 'B6', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (151, 'B7', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (152, 'B8', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (153, 'C1', 'PLATINUM', 330, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (154, 'C2', 'PLATINUM', 330, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (155, 'C3', 'PLATINUM', 330, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (156, 'C4', 'PLATINUM', 330, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (157, 'C5', 'PLATINUM', 330, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (158, 'C6', 'PLATINUM', 330, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (159, 'C7', 'PLATINUM', 330, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (160, 'C8', 'PLATINUM', 330, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (161, 'D1', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (162, 'D2', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (163, 'D3', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (164, 'D4', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (165, 'D5', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (166, 'D6', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (167, 'D7', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (168, 'D8', 'GOLD', 250, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (169, 'E1', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (170, 'E2', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (171, 'E3', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (172, 'E4', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (173, 'E5', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (174, 'E6', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (175, 'E7', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (176, 'E8', 'SILVER', 200, 'AVAILABLE', 4, NULL, 'INOX Nehru Place', NULL, NOW(), NOW()),
  (177, 'A3', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (178, 'A4', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (179, 'A5', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (180, 'A6', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (181, 'A7', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (182, 'A8', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (183, 'B1', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (184, 'B2', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (185, 'B3', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (186, 'B4', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (187, 'B5', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (188, 'B6', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (189, 'B7', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (190, 'B8', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (191, 'C1', 'PLATINUM', 350, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (192, 'C2', 'PLATINUM', 350, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (193, 'C3', 'PLATINUM', 350, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (194, 'C4', 'PLATINUM', 350, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (195, 'C5', 'PLATINUM', 350, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (196, 'C6', 'PLATINUM', 350, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (197, 'C7', 'PLATINUM', 350, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (198, 'C8', 'PLATINUM', 350, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (199, 'D1', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (200, 'D2', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (201, 'D3', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (202, 'D4', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (203, 'D5', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (204, 'D6', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (205, 'D7', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (206, 'D8', 'GOLD', 270, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (207, 'E1', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (208, 'E2', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (209, 'E3', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (210, 'E4', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (211, 'E5', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (212, 'E6', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (213, 'E7', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (214, 'E8', 'SILVER', 200, 'AVAILABLE', 5, NULL, 'AMC Forum Sujana Mall', NULL, NOW(), NOW()),
  (215, 'A3', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (216, 'A4', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (217, 'A5', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (218, 'A6', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (219, 'A7', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (220, 'A8', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (221, 'B1', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (222, 'B2', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (223, 'B3', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (224, 'B4', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (225, 'B5', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (226, 'B6', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (227, 'B7', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (228, 'B8', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (229, 'C1', 'PLATINUM', 320, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (230, 'C2', 'PLATINUM', 320, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (231, 'C3', 'PLATINUM', 320, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (232, 'C4', 'PLATINUM', 320, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (233, 'C5', 'PLATINUM', 320, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (234, 'C6', 'PLATINUM', 320, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (235, 'C7', 'PLATINUM', 320, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (236, 'C8', 'PLATINUM', 320, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (237, 'D1', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (238, 'D2', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (239, 'D3', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (240, 'D4', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (241, 'D5', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (242, 'D6', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (243, 'D7', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (244, 'D8', 'GOLD', 240, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (245, 'E1', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (246, 'E2', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (247, 'E3', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (248, 'E4', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (249, 'E5', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (250, 'E6', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (251, 'E7', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (252, 'E8', 'SILVER', 190, 'AVAILABLE', 6, NULL, 'PVR RK Salai', NULL, NOW(), NOW()),
  (253, 'A3', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (254, 'A4', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (255, 'A5', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (256, 'A6', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (257, 'A7', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (258, 'A8', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (259, 'B1', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (260, 'B2', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (261, 'B3', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (262, 'B4', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (263, 'B5', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (264, 'B6', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (265, 'B7', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (266, 'B8', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (267, 'C1', 'PLATINUM', 340, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (268, 'C2', 'PLATINUM', 340, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (269, 'C3', 'PLATINUM', 340, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (270, 'C4', 'PLATINUM', 340, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (271, 'C5', 'PLATINUM', 340, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (272, 'C6', 'PLATINUM', 340, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (273, 'C7', 'PLATINUM', 340, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (274, 'C8', 'PLATINUM', 340, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (275, 'D1', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (276, 'D2', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (277, 'D3', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (278, 'D4', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (279, 'D5', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (280, 'D6', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (281, 'D7', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (282, 'D8', 'GOLD', 260, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (283, 'E1', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (284, 'E2', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (285, 'E3', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (286, 'E4', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (287, 'E5', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (288, 'E6', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (289, 'E7', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (290, 'E8', 'SILVER', 200, 'AVAILABLE', 7, NULL, 'INOX Quest', NULL, NOW(), NOW()),
  (291, 'A3', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (292, 'A4', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (293, 'A5', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (294, 'A6', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (295, 'A7', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (296, 'A8', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (297, 'B1', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (298, 'B2', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (299, 'B3', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (300, 'B4', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (301, 'B5', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (302, 'B6', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (303, 'B7', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (304, 'B8', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (305, 'C1', 'PLATINUM', 340, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (306, 'C2', 'PLATINUM', 340, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (307, 'C3', 'PLATINUM', 340, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (308, 'C4', 'PLATINUM', 340, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (309, 'C5', 'PLATINUM', 340, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (310, 'C6', 'PLATINUM', 340, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (311, 'C7', 'PLATINUM', 340, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (312, 'C8', 'PLATINUM', 340, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (313, 'D1', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (314, 'D2', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (315, 'D3', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (316, 'D4', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (317, 'D5', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (318, 'D6', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (319, 'D7', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (320, 'D8', 'GOLD', 270, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (321, 'E1', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (322, 'E2', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (323, 'E3', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (324, 'E4', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (325, 'E5', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (326, 'E6', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (327, 'E7', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (328, 'E8', 'SILVER', 210, 'AVAILABLE', 8, NULL, 'Carnival Cinemas E-Square', NULL, NOW(), NOW()),
  (329, 'A3', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (330, 'A4', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (331, 'A5', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (332, 'A6', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (333, 'A7', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (334, 'A8', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (335, 'B1', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (336, 'B2', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (337, 'B3', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (338, 'B4', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (339, 'B5', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (340, 'B6', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (341, 'B7', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (342, 'B8', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (343, 'C1', 'PLATINUM', 335, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (344, 'C2', 'PLATINUM', 335, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (345, 'C3', 'PLATINUM', 335, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (346, 'C4', 'PLATINUM', 335, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (347, 'C5', 'PLATINUM', 335, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (348, 'C6', 'PLATINUM', 335, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (349, 'C7', 'PLATINUM', 335, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (350, 'C8', 'PLATINUM', 335, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (351, 'D1', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (352, 'D2', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (353, 'D3', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (354, 'D4', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (355, 'D5', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (356, 'D6', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (357, 'D7', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (358, 'D8', 'GOLD', 255, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (359, 'E1', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (360, 'E2', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (361, 'E3', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (362, 'E4', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (363, 'E5', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (364, 'E6', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (365, 'E7', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (366, 'E8', 'SILVER', 195, 'AVAILABLE', 9, NULL, 'PVR Nexus Koramangala', NULL, NOW(), NOW()),
  (367, 'A3', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (368, 'A4', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (369, 'A5', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (370, 'A6', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (371, 'A7', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (372, 'A8', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (373, 'B1', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (374, 'B2', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (375, 'B3', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (376, 'B4', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (377, 'B5', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (378, 'B6', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (379, 'B7', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (380, 'B8', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (381, 'C1', 'PLATINUM', 345, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (382, 'C2', 'PLATINUM', 345, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (383, 'C3', 'PLATINUM', 345, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (384, 'C4', 'PLATINUM', 345, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (385, 'C5', 'PLATINUM', 345, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (386, 'C6', 'PLATINUM', 345, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (387, 'C7', 'PLATINUM', 345, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (388, 'C8', 'PLATINUM', 345, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (389, 'D1', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (390, 'D2', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (391, 'D3', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (392, 'D4', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (393, 'D5', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (394, 'D6', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (395, 'D7', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (396, 'D8', 'GOLD', 265, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (397, 'E1', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (398, 'E2', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (399, 'E3', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (400, 'E4', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (401, 'E5', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (402, 'E6', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (403, 'E7', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (404, 'E8', 'SILVER', 215, 'AVAILABLE', 10, NULL, 'INOX R-City Mall', NULL, NOW(), NOW()),
  (405, 'A3', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (406, 'A4', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (407, 'A5', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (408, 'A6', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (409, 'A7', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (410, 'A8', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (411, 'B1', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (412, 'B2', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (413, 'B3', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (414, 'B4', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (415, 'B5', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (416, 'B6', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (417, 'B7', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (418, 'B8', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (419, 'C1', 'PLATINUM', 360, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (420, 'C2', 'PLATINUM', 360, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (421, 'C3', 'PLATINUM', 360, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (422, 'C4', 'PLATINUM', 360, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (423, 'C5', 'PLATINUM', 360, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (424, 'C6', 'PLATINUM', 360, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (425, 'C7', 'PLATINUM', 360, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (426, 'C8', 'PLATINUM', 360, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (427, 'D1', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (428, 'D2', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (429, 'D3', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (430, 'D4', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (431, 'D5', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (432, 'D6', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (433, 'D7', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (434, 'D8', 'GOLD', 265, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (435, 'E1', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (436, 'E2', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (437, 'E3', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (438, 'E4', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (439, 'E5', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (440, 'E6', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (441, 'E7', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (442, 'E8', 'SILVER', 205, 'AVAILABLE', 11, NULL, 'Cinepolis Manjeera', NULL, NOW(), NOW()),
  (443, 'A3', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (444, 'A4', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (445, 'A5', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (446, 'A6', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (447, 'A7', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (448, 'A8', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (449, 'B1', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (450, 'B2', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (451, 'B3', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (452, 'B4', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (453, 'B5', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (454, 'B6', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (455, 'B7', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (456, 'B8', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (457, 'C1', 'PLATINUM', 355, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (458, 'C2', 'PLATINUM', 355, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (459, 'C3', 'PLATINUM', 355, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (460, 'C4', 'PLATINUM', 355, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (461, 'C5', 'PLATINUM', 355, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (462, 'C6', 'PLATINUM', 355, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (463, 'C7', 'PLATINUM', 355, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (464, 'C8', 'PLATINUM', 355, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (465, 'D1', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (466, 'D2', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (467, 'D3', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (468, 'D4', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (469, 'D5', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (470, 'D6', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (471, 'D7', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (472, 'D8', 'GOLD', 275, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (473, 'E1', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (474, 'E2', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (475, 'E3', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (476, 'E4', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (477, 'E5', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (478, 'E6', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (479, 'E7', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW()),
  (480, 'E8', 'SILVER', 195, 'AVAILABLE', 12, NULL, 'Escape Cinemas Express Avenue', NULL, NOW(), NOW());

-- 4) Complete show_seats for shows 1-4 (ids auto-assigned).
INSERT INTO show_seats (show_id, seat_id, seat_status, booked_by_user_id, created_at, updated_at) VALUES
  -- Show 1 @ Orion (Action Blast): remaining seats 3,4,5,30-64
  (1, 3, 'BOOKED', 1, NOW(), NOW()), (1, 4, 'BOOKED', 1, NOW(), NOW()), (1, 5, 'BLOCKED', 2, NOW(), NOW()),
  (1, 30, 'AVAILABLE', NULL, NOW(), NOW()), (1, 31, 'AVAILABLE', NULL, NOW(), NOW()), (1, 32, 'AVAILABLE', NULL, NOW(), NOW()), (1, 33, 'AVAILABLE', NULL, NOW(), NOW()), (1, 34, 'AVAILABLE', NULL, NOW(), NOW()), (1, 35, 'AVAILABLE', NULL, NOW(), NOW()),
  (1, 36, 'AVAILABLE', NULL, NOW(), NOW()), (1, 37, 'AVAILABLE', NULL, NOW(), NOW()), (1, 38, 'AVAILABLE', NULL, NOW(), NOW()), (1, 39, 'AVAILABLE', NULL, NOW(), NOW()), (1, 40, 'AVAILABLE', NULL, NOW(), NOW()), (1, 41, 'AVAILABLE', NULL, NOW(), NOW()),
  (1, 42, 'AVAILABLE', NULL, NOW(), NOW()), (1, 43, 'AVAILABLE', NULL, NOW(), NOW()), (1, 44, 'AVAILABLE', NULL, NOW(), NOW()), (1, 45, 'AVAILABLE', NULL, NOW(), NOW()), (1, 46, 'AVAILABLE', NULL, NOW(), NOW()), (1, 47, 'AVAILABLE', NULL, NOW(), NOW()), (1, 48, 'AVAILABLE', NULL, NOW(), NOW()),
  (1, 49, 'AVAILABLE', NULL, NOW(), NOW()), (1, 50, 'AVAILABLE', NULL, NOW(), NOW()), (1, 51, 'AVAILABLE', NULL, NOW(), NOW()), (1, 52, 'AVAILABLE', NULL, NOW(), NOW()), (1, 53, 'AVAILABLE', NULL, NOW(), NOW()), (1, 54, 'AVAILABLE', NULL, NOW(), NOW()), (1, 55, 'AVAILABLE', NULL, NOW(), NOW()), (1, 56, 'AVAILABLE', NULL, NOW(), NOW()),
  (1, 57, 'AVAILABLE', NULL, NOW(), NOW()), (1, 58, 'AVAILABLE', NULL, NOW(), NOW()), (1, 59, 'AVAILABLE', NULL, NOW(), NOW()), (1, 60, 'AVAILABLE', NULL, NOW(), NOW()), (1, 61, 'AVAILABLE', NULL, NOW(), NOW()), (1, 62, 'AVAILABLE', NULL, NOW(), NOW()), (1, 63, 'AVAILABLE', NULL, NOW(), NOW()), (1, 64, 'AVAILABLE', NULL, NOW(), NOW()),
  -- Show 2 @ Orion (RomCom Nights): remaining seats 3,4,5,30-64 (seat 2 already BLOCKED above)
  (2, 3, 'BOOKED', 1, NOW(), NOW()), (2, 4, 'BOOKED', 1, NOW(), NOW()), (2, 5, 'BLOCKED', 2, NOW(), NOW()),
  (2, 30, 'AVAILABLE', NULL, NOW(), NOW()), (2, 31, 'AVAILABLE', NULL, NOW(), NOW()), (2, 32, 'AVAILABLE', NULL, NOW(), NOW()), (2, 33, 'AVAILABLE', NULL, NOW(), NOW()), (2, 34, 'AVAILABLE', NULL, NOW(), NOW()), (2, 35, 'AVAILABLE', NULL, NOW(), NOW()),
  (2, 36, 'AVAILABLE', NULL, NOW(), NOW()), (2, 37, 'AVAILABLE', NULL, NOW(), NOW()), (2, 38, 'AVAILABLE', NULL, NOW(), NOW()), (2, 39, 'AVAILABLE', NULL, NOW(), NOW()), (2, 40, 'AVAILABLE', NULL, NOW(), NOW()), (2, 41, 'AVAILABLE', NULL, NOW(), NOW()),
  (2, 42, 'AVAILABLE', NULL, NOW(), NOW()), (2, 43, 'AVAILABLE', NULL, NOW(), NOW()), (2, 44, 'AVAILABLE', NULL, NOW(), NOW()), (2, 45, 'AVAILABLE', NULL, NOW(), NOW()), (2, 46, 'AVAILABLE', NULL, NOW(), NOW()), (2, 47, 'AVAILABLE', NULL, NOW(), NOW()), (2, 48, 'AVAILABLE', NULL, NOW(), NOW()),
  (2, 49, 'AVAILABLE', NULL, NOW(), NOW()), (2, 50, 'AVAILABLE', NULL, NOW(), NOW()), (2, 51, 'AVAILABLE', NULL, NOW(), NOW()), (2, 52, 'AVAILABLE', NULL, NOW(), NOW()), (2, 53, 'AVAILABLE', NULL, NOW(), NOW()), (2, 54, 'AVAILABLE', NULL, NOW(), NOW()), (2, 55, 'AVAILABLE', NULL, NOW(), NOW()), (2, 56, 'AVAILABLE', NULL, NOW(), NOW()),
  (2, 57, 'AVAILABLE', NULL, NOW(), NOW()), (2, 58, 'AVAILABLE', NULL, NOW(), NOW()), (2, 59, 'AVAILABLE', NULL, NOW(), NOW()), (2, 60, 'AVAILABLE', NULL, NOW(), NOW()), (2, 61, 'AVAILABLE', NULL, NOW(), NOW()), (2, 62, 'AVAILABLE', NULL, NOW(), NOW()), (2, 63, 'AVAILABLE', NULL, NOW(), NOW()), (2, 64, 'AVAILABLE', NULL, NOW(), NOW()),
  -- Show 3 @ Phoenix (Action Blast): remaining seats 8,9,65-100
  (3, 8, 'AVAILABLE', NULL, NOW(), NOW()), (3, 9, 'AVAILABLE', NULL, NOW(), NOW()),
  (3, 65, 'AVAILABLE', NULL, NOW(), NOW()), (3, 66, 'AVAILABLE', NULL, NOW(), NOW()), (3, 67, 'AVAILABLE', NULL, NOW(), NOW()), (3, 68, 'AVAILABLE', NULL, NOW(), NOW()), (3, 69, 'AVAILABLE', NULL, NOW(), NOW()), (3, 70, 'AVAILABLE', NULL, NOW(), NOW()),
  (3, 71, 'AVAILABLE', NULL, NOW(), NOW()), (3, 72, 'AVAILABLE', NULL, NOW(), NOW()), (3, 73, 'AVAILABLE', NULL, NOW(), NOW()), (3, 74, 'AVAILABLE', NULL, NOW(), NOW()), (3, 75, 'AVAILABLE', NULL, NOW(), NOW()), (3, 76, 'AVAILABLE', NULL, NOW(), NOW()), (3, 77, 'AVAILABLE', NULL, NOW(), NOW()),
  (3, 78, 'AVAILABLE', NULL, NOW(), NOW()), (3, 79, 'AVAILABLE', NULL, NOW(), NOW()), (3, 80, 'AVAILABLE', NULL, NOW(), NOW()), (3, 81, 'AVAILABLE', NULL, NOW(), NOW()), (3, 82, 'AVAILABLE', NULL, NOW(), NOW()), (3, 83, 'AVAILABLE', NULL, NOW(), NOW()), (3, 84, 'AVAILABLE', NULL, NOW(), NOW()),
  (3, 85, 'AVAILABLE', NULL, NOW(), NOW()), (3, 86, 'AVAILABLE', NULL, NOW(), NOW()), (3, 87, 'AVAILABLE', NULL, NOW(), NOW()), (3, 88, 'AVAILABLE', NULL, NOW(), NOW()), (3, 89, 'AVAILABLE', NULL, NOW(), NOW()), (3, 90, 'AVAILABLE', NULL, NOW(), NOW()), (3, 91, 'AVAILABLE', NULL, NOW(), NOW()), (3, 92, 'AVAILABLE', NULL, NOW(), NOW()),
  (3, 93, 'AVAILABLE', NULL, NOW(), NOW()), (3, 94, 'AVAILABLE', NULL, NOW(), NOW()), (3, 95, 'AVAILABLE', NULL, NOW(), NOW()), (3, 96, 'AVAILABLE', NULL, NOW(), NOW()), (3, 97, 'AVAILABLE', NULL, NOW(), NOW()), (3, 98, 'AVAILABLE', NULL, NOW(), NOW()), (3, 99, 'AVAILABLE', NULL, NOW(), NOW()), (3, 100, 'AVAILABLE', NULL, NOW(), NOW()),
  -- Show 4 @ Phoenix (Laugh Out Loud): remaining seats 65-100
  (4, 65, 'AVAILABLE', NULL, NOW(), NOW()), (4, 66, 'AVAILABLE', NULL, NOW(), NOW()), (4, 67, 'AVAILABLE', NULL, NOW(), NOW()), (4, 68, 'AVAILABLE', NULL, NOW(), NOW()), (4, 69, 'AVAILABLE', NULL, NOW(), NOW()), (4, 70, 'AVAILABLE', NULL, NOW(), NOW()),
  (4, 71, 'AVAILABLE', NULL, NOW(), NOW()), (4, 72, 'AVAILABLE', NULL, NOW(), NOW()), (4, 73, 'AVAILABLE', NULL, NOW(), NOW()), (4, 74, 'AVAILABLE', NULL, NOW(), NOW()), (4, 75, 'AVAILABLE', NULL, NOW(), NOW()), (4, 76, 'AVAILABLE', NULL, NOW(), NOW()), (4, 77, 'AVAILABLE', NULL, NOW(), NOW()),
  (4, 78, 'AVAILABLE', NULL, NOW(), NOW()), (4, 79, 'AVAILABLE', NULL, NOW(), NOW()), (4, 80, 'AVAILABLE', NULL, NOW(), NOW()), (4, 81, 'AVAILABLE', NULL, NOW(), NOW()), (4, 82, 'AVAILABLE', NULL, NOW(), NOW()), (4, 83, 'AVAILABLE', NULL, NOW(), NOW()), (4, 84, 'AVAILABLE', NULL, NOW(), NOW()),
  (4, 85, 'AVAILABLE', NULL, NOW(), NOW()), (4, 86, 'AVAILABLE', NULL, NOW(), NOW()), (4, 87, 'AVAILABLE', NULL, NOW(), NOW()), (4, 88, 'AVAILABLE', NULL, NOW(), NOW()), (4, 89, 'AVAILABLE', NULL, NOW(), NOW()), (4, 90, 'AVAILABLE', NULL, NOW(), NOW()), (4, 91, 'AVAILABLE', NULL, NOW(), NOW()), (4, 92, 'AVAILABLE', NULL, NOW(), NOW()),
  (4, 93, 'AVAILABLE', NULL, NOW(), NOW()), (4, 94, 'AVAILABLE', NULL, NOW(), NOW()), (4, 95, 'AVAILABLE', NULL, NOW(), NOW()), (4, 96, 'AVAILABLE', NULL, NOW(), NOW()), (4, 97, 'AVAILABLE', NULL, NOW(), NOW()), (4, 98, 'AVAILABLE', NULL, NOW(), NOW()), (4, 99, 'AVAILABLE', NULL, NOW(), NOW()), (4, 100, 'AVAILABLE', NULL, NOW(), NOW());

-- 5) Complete show_seats for shows 5-15 (ids auto-assigned).
INSERT INTO show_seats (show_id, seat_id, seat_status, booked_by_user_id, created_at, updated_at) VALUES
  (5, 101, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 102, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 103, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 104, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 105, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 106, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 107, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 108, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 109, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 110, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 111, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 112, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 113, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 114, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 115, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 116, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 117, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 118, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 119, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 120, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 121, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 122, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 123, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 124, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 125, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 126, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 127, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 128, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 129, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 130, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 131, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 132, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 133, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 134, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 135, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 136, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 137, 'AVAILABLE', NULL, NOW(), NOW()),
  (5, 138, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 101, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 102, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 103, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 104, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 105, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 106, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 107, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 108, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 109, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 110, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 111, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 112, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 113, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 114, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 115, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 116, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 117, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 118, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 119, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 120, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 121, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 122, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 123, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 124, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 125, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 126, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 127, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 128, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 129, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 130, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 131, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 132, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 133, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 134, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 135, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 136, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 137, 'AVAILABLE', NULL, NOW(), NOW()),
  (6, 138, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 139, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 140, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 141, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 142, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 143, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 144, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 145, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 146, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 147, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 148, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 149, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 150, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 151, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 152, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 153, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 154, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 155, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 156, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 157, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 158, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 159, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 160, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 161, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 162, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 163, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 164, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 165, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 166, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 167, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 168, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 169, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 170, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 171, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 172, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 173, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 174, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 175, 'AVAILABLE', NULL, NOW(), NOW()),
  (7, 176, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 177, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 178, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 179, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 180, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 181, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 182, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 183, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 184, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 185, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 186, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 187, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 188, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 189, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 190, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 191, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 192, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 193, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 194, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 195, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 196, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 197, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 198, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 199, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 200, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 201, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 202, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 203, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 204, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 205, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 206, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 207, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 208, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 209, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 210, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 211, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 212, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 213, 'AVAILABLE', NULL, NOW(), NOW()),
  (8, 214, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 215, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 216, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 217, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 218, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 219, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 220, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 221, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 222, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 223, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 224, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 225, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 226, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 227, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 228, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 229, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 230, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 231, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 232, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 233, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 234, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 235, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 236, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 237, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 238, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 239, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 240, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 241, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 242, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 243, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 244, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 245, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 246, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 247, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 248, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 249, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 250, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 251, 'AVAILABLE', NULL, NOW(), NOW()),
  (9, 252, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 253, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 254, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 255, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 256, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 257, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 258, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 259, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 260, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 261, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 262, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 263, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 264, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 265, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 266, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 267, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 268, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 269, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 270, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 271, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 272, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 273, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 274, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 275, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 276, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 277, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 278, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 279, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 280, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 281, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 282, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 283, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 284, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 285, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 286, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 287, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 288, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 289, 'AVAILABLE', NULL, NOW(), NOW()),
  (10, 290, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 291, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 292, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 293, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 294, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 295, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 296, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 297, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 298, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 299, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 300, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 301, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 302, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 303, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 304, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 305, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 306, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 307, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 308, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 309, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 310, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 311, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 312, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 313, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 314, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 315, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 316, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 317, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 318, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 319, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 320, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 321, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 322, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 323, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 324, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 325, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 326, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 327, 'AVAILABLE', NULL, NOW(), NOW()),
  (11, 328, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 329, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 330, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 331, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 332, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 333, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 334, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 335, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 336, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 337, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 338, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 339, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 340, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 341, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 342, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 343, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 344, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 345, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 346, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 347, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 348, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 349, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 350, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 351, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 352, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 353, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 354, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 355, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 356, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 357, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 358, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 359, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 360, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 361, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 362, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 363, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 364, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 365, 'AVAILABLE', NULL, NOW(), NOW()),
  (12, 366, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 367, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 368, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 369, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 370, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 371, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 372, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 373, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 374, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 375, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 376, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 377, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 378, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 379, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 380, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 381, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 382, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 383, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 384, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 385, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 386, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 387, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 388, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 389, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 390, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 391, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 392, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 393, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 394, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 395, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 396, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 397, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 398, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 399, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 400, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 401, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 402, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 403, 'AVAILABLE', NULL, NOW(), NOW()),
  (13, 404, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 405, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 406, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 407, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 408, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 409, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 410, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 411, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 412, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 413, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 414, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 415, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 416, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 417, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 418, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 419, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 420, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 421, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 422, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 423, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 424, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 425, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 426, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 427, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 428, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 429, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 430, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 431, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 432, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 433, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 434, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 435, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 436, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 437, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 438, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 439, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 440, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 441, 'AVAILABLE', NULL, NOW(), NOW()),
  (14, 442, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 443, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 444, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 445, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 446, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 447, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 448, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 449, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 450, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 451, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 452, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 453, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 454, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 455, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 456, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 457, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 458, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 459, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 460, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 461, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 462, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 463, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 464, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 465, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 466, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 467, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 468, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 469, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 470, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 471, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 472, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 473, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 474, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 475, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 476, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 477, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 478, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 479, 'AVAILABLE', NULL, NOW(), NOW()),
  (15, 480, 'AVAILABLE', NULL, NOW(), NOW());

